services:
  - type: web
    name: macro-datahub
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NO_BROWSER
        value: "1"
